from enum import Enum as PyEnum


class PapelBanca(PyEnum):
    ORIENTADOR = "ORIENTADOR"
    COORIENTADOR = "COORIENTADOR"
    AVALIADOR_INTERNO = "AVALIADOR_INTERNO"
    AVALIADOR_EXTERNO = "AVALIADOR_EXTERNO"
    SUPLENTE = "SUPLENTE"
