from enum import Enum as PyEnum


class StatusDeposito(PyEnum):
    AGUARDANDO_ENVIO = "AGUARDANDO_ENVIO"
    EM_REVISAO = "EM_REVISAO"
    DEVOLVIDO_PARA_CORRECAO = "DEVOLVIDO_PARA_CORRECAO"
    APROVADO = "APROVADO"
    DEPOSITADO = "DEPOSITADO"


class TipoDocumentoDeposito(PyEnum):
    TCC_FINAL = "TCC_FINAL"
    ATA_DEFESA = "ATA_DEFESA"
    FOLHA_APROVACAO = "FOLHA_APROVACAO"
    FORMULARIOS = "FORMULARIOS"
    DECLARACOES = "DECLARACOES"
