ALTER TYPE "StatusTCC" ADD VALUE IF NOT EXISTS 'SEM_ORIENTADOR';
ALTER TYPE "AcaoEdicaoTCC" ADD VALUE IF NOT EXISTS 'ACEITE_ORIENTACAO';
ALTER TYPE "AcaoEdicaoTCC" ADD VALUE IF NOT EXISTS 'RECUSA_ORIENTACAO';

ALTER TABLE "tccs"
ADD COLUMN "observacao_orientador" TEXT;

ALTER TABLE "tcc_edit_logs"
ADD COLUMN "observacao" TEXT;
